### ISSUE TITLE
Hello, what does this project do?

### ISSUE THREAD

**Issue by zoain-it** [switch-lan-play/wlan-play#1]

**Comment by spacemeowx2** [comment]
This project tried to control wireless adapter to connect with Nintendo Switch via local wireless.

**Comment by zoain-it** [comment]
> This project tried to control wireless adapter to connect with Nintendo Switch via local wireless.

That means it can pull two Nintendo Switch with different WIFI into a fake local wifi?

**Comment by spacemeowx2** [comment]
It could only if this project finished, but it's not

**Comment by zoain-it** [comment]
> It could only if this project finished, but it's not

Okay, I see, so will it continue to be developed?
